env:
  browser: true
  es6: true
  node: true
extends:
  - '@ridedott/eslint-config'
  - 'plugin:react/recommended'
  - 'plugin:jsx-a11y/recommended'
  - 'plugin:react-hooks/recommended'
overrides:
  - files: ./src/**/*spec.ts
    rules:
      '@typescript-eslint/no-magic-numbers': 'off'
parserOptions:
  ecmaVersion: 10
  project: tsconfig.json
  sourceType: module
rules:
  capitalized-comments:
    - error
    - always
    - ignoreConsecutiveComments: true
  func-style: 'off'
  init-declarations: 'off'
  immutable/no-let: 'off'
  immutable/no-mutation: 'off'
  immutable/no-this: 'off'
  '@typescript-eslint/restrict-template-expressions': 'off'
  '@typescript-eslint/strict-boolean-expressions': 'off'
  max-lines-per-function: 'off'
  max-params: 'off'
  max-statements: 'off'
  no-implicit-coercion: 'off'
  react/prop-types: 'off'
  unicorn/consistent-function-scoping: 'off'
  unicorn/filename-case:
    - error
    - case: kebabCase
  unicorn/prevent-abbreviations:
    - error
    - whitelist:
        useRef: true
