env:
  browser: true
  es2020: true
extends:
  - '@ridedott/eslint-config'
  - 'plugin:react/recommended'
  - 'plugin:jsx-a11y/recommended'
  - 'plugin:react-hooks/recommended'
overrides:
  - files: ./src/**/__tests__/*.{ts,tsx}
    rules:
      '@typescript-eslint/explicit-function-return-type': 'off'
      '@typescript-eslint/no-magic-numbers': 'off'
      'jest/prefer-expect-assertions': 'off'
parserOptions:
  ecmaVersion: 10
  project: tsconfig.json
  sourceType: module
rules:
  capitalized-comments:
    - error
    - always
    - ignoreConsecutiveComments: true
  func-style: 'off'
  init-declarations: 'off'
  immutable/no-let: 'off'
  immutable/no-mutation: 'off'
  immutable/no-this: 'off'
  jest/consistent-test-it: ['error', { fn: 'test', withinDescribe: 'test' }]
  jest/expect-expect: 'off'
  '@typescript-eslint/init-declarations': 'off'
  '@typescript-eslint/member-ordering': 'off'
  '@typescript-eslint/restrict-template-expressions': 'off'
  '@typescript-eslint/sort-type-union-intersection-members': 'off'
  '@typescript-eslint/strict-boolean-expressions': 'off'
  max-lines-per-function: 'off'
  max-params: 'off'
  max-statements: 'off'
  multiline-comment-style: 'off'
  no-implicit-coercion: 'off'
  react/prop-types: 'off'
  sort-keys: 'off'
  unicorn/consistent-function-scoping: 'off'
  unicorn/filename-case:
    - error
    - case: kebabCase
  unicorn/expiring-todo-comments: 'off'
  unicorn/prevent-abbreviations: 'off'
